name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish-Common
      run: dotnet pack -c Release -o . Lljxww.Common/Lljxww.Common.csproj && dotnet nuget push *.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Publish-CSRedis
      run: dotnet pack -c Release -o . Lljxww.Common.CSRedis.Extensions/Lljxww.Common.CSRedis.Extensions.csproj && dotnet nuget push *.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Publish-ApiCaller
      run: dotnet pack -c Release -o . Lljxww.Common.ApiCaller/Lljxww.Common.ApiCaller.csproj && dotnet nuget push *.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
       
    - name: Publish-EntityFramework
      run: dotnet pack -c Release -o . Lljxww.Common.EntityFramework.Extensions/Lljxww.Common.EntityFramework.Extensions.csproj && dotnet nuget push *.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Publish-Dapper
      run: dotnet pack -c Release -o . Lljxww.Common.Dapper.Extensions/Lljxww.Common.Dapper.Extensions.csproj && dotnet nuget push *.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
